# Generated by Django 4.0.1 on 2022-04-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('SUPERADMIN', 'SUPERADMIN')], max_length=15, null=True),
        ),
    ]
