# Generated by Django 4.0.1 on 2022-05-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='zone',
            field=models.CharField(default='zone', max_length=100),
            preserve_default=False,
        ),
    ]
