# Generated by Django 4.0.1 on 2022-05-15 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_order_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_charges',
        ),
    ]
