# Generated by Django 4.0.1 on 2022-03-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_product_price_alter_product_promo_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='promo_price',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
