# Generated by Django 4.0.1 on 2022-05-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='image_url',
            field=models.CharField(default='ljin', max_length=255),
            preserve_default=False,
        ),
    ]
