# Generated by Django 4.0.1 on 2022-05-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_orderproduct_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_string',
            field=models.TextField(default='category'),
            preserve_default=False,
        ),
    ]
