# Generated by Django 4.0.1 on 2022-03-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_product_variant_value_alter_product_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='principal_image',
            field=models.ImageField(null=True, upload_to='products'),
        ),
    ]
