# Generated by Django 4.0.1 on 2022-04-30 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_product_principal_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZoneInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=100)),
                ('delivery_charges', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='sales.category'),
        ),
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sales.product'),
        ),
        migrations.AlterField(
            model_name='video',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='sales.product'),
        ),
    ]
