# Generated by Django 3.2.13 on 2022-06-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_remove_product_category_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
